sudo: required

# Install Docker
services:
  - docker

# Execute Logic
script:
  - echo "Hello Students!"

after_success:
 # Build all the docker files
  - docker build -t harshii/zomato-shapeai-client ./client
  - docker build -t harshii/zomato-shapeai-server ./server
  - docker build -t harshii/zomato-shapeai-nginx ./nginx
 
 # log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # push to docker hub
  - docker push harshii/zomato-shapeai-client
  - docker push harshii/zomato-shapeai-server
  - docker push harshii/zomato-shapeai-nginx 

  deploy:
  # deploy to AWS EBS
  provider: elasticbeanstalk
  region: us-east-2
  app: Zomato-clone-shapeai
  env: Zomatocloneshapeai-env
  bucket_name: elasticbeanstalk-us-east-2-767491905585
  bucket_path: zomatoshapeai
  on: 
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET

